project_id = "dvisdjvzwbfklrpzsuhe"

[functions.mp-create-preference]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.create-withdrawal-request]
verify_jwt = false

[functions.update-withdrawal-request]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.send-feedback]
verify_jwt = false
